server:
  port: 8081
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
       - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - "*"
            allowed-headers:
              - "*"
      routes:
      - id: enquiry
        uri: lb://CUSTOMER-ENQUIRY
        predicates:
        - Path=/enquiry/**
        
        
      - id: login
        uri: lb://LOGIN
        predicates:
        - Path=/login/**
        
      - id: report
        uri: lb://R
        predicates:
        - Path=/report/**
        
      - id: registration
        uri: lb://EMPLOYEE-REGISTRATION
        predicates:
        - Path=/reg/**     
      

#
#     
#      - id: Indigo
#        uri: lb://INDIGO
#        predicates:
#        - Path=/IN/**
#        
#      - id: Airindia
#        uri: lb://AIRINDIA
#        predicates:
#       - Path=/AI/**
        

     
  main:
    web-application-type: reactive

                   
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
        


      