server:
  port: 9093
spring:
  application:
    name: EMPLOYEE-REGISTRATION
  #client:
  #  serverUrl:
   #   defaultZOne: ': http://localhost:8761/eureka'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/carloan
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  management:
    endpoints:
      web:
        exposure:
          include: '''*'''
  properties:
    hibernate-dilect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 7MB


